rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
notifications:
  email:
    - carlos@apache.org
    - tim@github.com
env:
  - PUPPET_VERSION=2.7.25
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.4.2

before_script:
  - puppet --version

matrix:
  allow_failures:
    - rvm: 2.1.0 # broken in puppet < 3.5.0 https://tickets.puppetlabs.com/browse/PUP-1243
