rvm:
  - 1.8.7
  - 1.9.3
notifications:
  email:
    - tim@github.com
env:
  - PUPPET_VERSION=2.7.25
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.4.2

before_install:
  - gem --version
  - gem update --system #  todo: workaround for https://github.com/rubygems/rubygems/pull/763

before_script:
  - bundle list
